# Generated by Django 5.0.3 on 2025-07-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(null=True),
        ),
    ]
