# Generated by Django 5.0.3 on 2025-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_core', '0003_diaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
