# Generated by Django 5.0.3 on 2025-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_core', '0004_alter_customuser_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
