# Generated by Django 5.2.4 on 2025-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_core', '0006_customuser_email_confirmation_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceitem',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
