# Generated by Django 5.2.4 on 2025-09-19 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_core', '0007_alter_practiceitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='daily_target',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='practiceitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
